<?php

//var_dump($_POST);
//echo "<br>";
//var_dump($_FILES);

 if (!function_exists('wp_handle_upload')) {
    require_once(ABSPATH . 'wp-admin/includes/file.php');
}

$uploadedfile = $_FILES['file'];
$upload_overrides = array('test_form' => false);
$movefile = wp_handle_upload($uploadedfile, $upload_overrides);

// echo $movefile['url'];
if ($movefile && !isset($movefile['error'])) {
  //echo "File Upload Successfully";
} else {
 /**
  * Error generated by _wp_handle_upload()
  * @see _wp_handle_upload() in wp-admin/includes/file.php
  */
 //echo $movefile['error'];
}
die();

?>
